"""step114_notificacao_preferencias

Revision ID: 6a63047d1156
Revises: step34_automacoes_agendamento
Create Date: 2026-05-02 03:43:08.514336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a63047d1156'
down_revision = 'step34_automacoes_agendamento'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacoes_preferencias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=False),
    sa.Column('email_ativo', sa.Boolean(), nullable=False),
    sa.Column('sistema_ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacoes_preferencias_tenant_id'), 'notificacoes_preferencias', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notificacoes_preferencias_usuario_id'), 'notificacoes_preferencias', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notificacoes_preferencias_usuario_id'), table_name='notificacoes_preferencias')
    op.drop_index(op.f('ix_notificacoes_preferencias_tenant_id'), table_name='notificacoes_preferencias')
    op.drop_table('notificacoes_preferencias')
    # ### end Alembic commands ###
