"""update_compras_pedidos_step_150

Revision ID: a9096a0db78f
Revises: d59f78311bad
Create Date: 2026-05-03 03:41:12.801554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9096a0db78f'
down_revision: Union[str, Sequence[str], None] = 'd59f78311bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras_pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitacao_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('cotacao_id', sa.Uuid(), nullable=True))
        # Making these nullable to avoid migration failure on existing data
        batch_op.add_column(sa.Column('fornecedor_nome', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('fornecedor_contato', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('item_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('deposito_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('quantidade', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('unidade', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('valor_unitario', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valor_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
        
        batch_op.alter_column('usuario_solicitante_id',
               existing_type=sa.UUID(),
               nullable=True)
        
        batch_op.create_index(batch_op.f('ix_compras_pedidos_cotacao_id'), ['cotacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compras_pedidos_deposito_id'), ['deposito_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compras_pedidos_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compras_pedidos_solicitacao_id'), ['solicitacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compras_pedidos_status'), ['status'], unique=False)
        
        batch_op.create_foreign_key('fk_pedido_item', 'cadastros_produtos', ['item_id'], ['id'])
        batch_op.create_foreign_key('fk_pedido_cotacao', 'compras_cotacoes', ['cotacao_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_pedido_deposito', 'estoque_depositos', ['deposito_id'], ['id'])
        batch_op.create_foreign_key('fk_pedido_solicitacao', 'compras_solicitacoes', ['solicitacao_id'], ['id'], ondelete='SET NULL')
        
        # We don't drop columns yet to avoid data loss if needed, but the prompt says to update the model.
        # batch_op.drop_column('data_recebimento')
        # batch_op.drop_column('deposito_destino_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras_pedidos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pedido_solicitacao', type_='foreignkey')
        batch_op.drop_constraint('fk_pedido_deposito', type_='foreignkey')
        batch_op.drop_constraint('fk_pedido_cotacao', type_='foreignkey')
        batch_op.drop_constraint('fk_pedido_item', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_compras_pedidos_status'))
        batch_op.drop_index(batch_op.f('ix_compras_pedidos_solicitacao_id'))
        batch_op.drop_index(batch_op.f('ix_compras_pedidos_item_id'))
        batch_op.drop_index(batch_op.f('ix_compras_pedidos_deposito_id'))
        batch_op.drop_index(batch_op.f('ix_compras_pedidos_cotacao_id'))
        batch_op.alter_column('usuario_solicitante_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('valor_total')
        batch_op.drop_column('valor_unitario')
        batch_op.drop_column('unidade')
        batch_op.drop_column('quantidade')
        batch_op.drop_column('deposito_id')
        batch_op.drop_column('item_id')
        batch_op.drop_column('fornecedor_contato')
        batch_op.drop_column('fornecedor_nome')
        batch_op.drop_column('cotacao_id')
        batch_op.drop_column('solicitacao_id')
    # ### end Alembic commands ###
