"""add_intelligence_alerts_to_cotacoes

Revision ID: b3e0c50368da
Revises: a9096a0db78f
Create Date: 2026-05-03 04:31:59.344584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3e0c50368da'
down_revision: Union[str, Sequence[str], None] = 'a9096a0db78f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compras_cotacoes', sa.Column('acima_media', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('compras_cotacoes', sa.Column('percentual_acima_media', sa.Float(), nullable=True))
    op.add_column('compras_cotacoes', sa.Column('mensagem_alerta', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compras_cotacoes', 'mensagem_alerta')
    op.drop_column('compras_cotacoes', 'percentual_acima_media')
    op.drop_column('compras_cotacoes', 'acima_media')
    # ### end Alembic commands ###

    # ### end Alembic commands ###
